import Head from "next/head";
import { Footer, Main } from "../components/custom-styles";
import Header from "../components/header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Drello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Header />
      </Main>
      <Footer>Setunas</Footer>
    </>
  );
}
